services:
  backend_service:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres_service

  postgres_service:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=1
    ports:
      - "5432:5432"

  redis_service:
    image: redis:alpine
    ports:
      - "6379:6379"

