"""initial commit

Revision ID: 3ff0137cdb9d
Revises: d04326331f63
Create Date: 2025-09-02 14:35:57.684251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ff0137cdb9d'
down_revision: Union[str, Sequence[str], None] = 'd04326331f63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.drop_column('user', 'password')
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.add_column('user', sa.Column('password', sa.String(), nullable=True))
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
